//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 07:36:04 PM CET 
//


package com.xml.vakcinacija.model.saglasnost;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

import com.xml.vakcinacija.model.Proizvodjac;
import com.xml.vakcinacija.model.PunoIme;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hajduk package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoNezeljanaReakcija_QNAME = new QName("http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", "NezeljanaReakcija");
    private final static QName _SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoDatumDavanjaVakcine_QNAME = new QName("http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", "DatumDavanjaVakcine");
    private final static QName _SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoNazivVakcine_QNAME = new QName("http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", "NazivVakcine");
    private final static QName _SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoSerijaVakcine_QNAME = new QName("http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", "SerijaVakcine");
    private final static QName _SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoProizvodjac_QNAME = new QName("http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", "Proizvodjac");
    private final static QName _SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoNacinDavanjeVakcine_QNAME = new QName("http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", "NacinDavanjeVakcine");
    private final static QName _SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoEkstremitet_QNAME = new QName("http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", "Ekstremitet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hajduk
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Saglasnost }
     * 
     */
    public Saglasnost createSaglasnost() {
        return new Saglasnost();
    }

    /**
     * Create an instance of {@link Saglasnost.ZdravstveniRadnikSaglasnost }
     * 
     */
    public Saglasnost.ZdravstveniRadnikSaglasnost createSaglasnostZdravstveniRadnikSaglasnost() {
        return new Saglasnost.ZdravstveniRadnikSaglasnost();
    }

    /**
     * Create an instance of {@link Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac }
     * 
     */
    public Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac createSaglasnostZdravstveniRadnikSaglasnostObrazac() {
        return new Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost }
     * 
     */
    public Saglasnost.PacijentSaglasnost createSaglasnostPacijentSaglasnost() {
        return new Saglasnost.PacijentSaglasnost();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.LicneInformacije }
     * 
     */
    public Saglasnost.PacijentSaglasnost.LicneInformacije createSaglasnostPacijentSaglasnostLicneInformacije() {
        return new Saglasnost.PacijentSaglasnost.LicneInformacije();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo }
     * 
     */
    public Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo createSaglasnostPacijentSaglasnostLicneInformacijeDrzavljanstvo() {
        return new Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.StranoDrzavljanstvo }
     * 
     */
    public Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.StranoDrzavljanstvo createSaglasnostPacijentSaglasnostLicneInformacijeDrzavljanstvoStranoDrzavljanstvo() {
        return new Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.StranoDrzavljanstvo();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.RepublikaSrbija }
     * 
     */
    public Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.RepublikaSrbija createSaglasnostPacijentSaglasnostLicneInformacijeDrzavljanstvoRepublikaSrbija() {
        return new Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.RepublikaSrbija();
    }

    /**
     * Create an instance of {@link PunoIme }
     * 
     */
    public PunoIme createPunoIme() {
        return new PunoIme();
    }

    /**
     * Create an instance of {@link Saglasnost.ZdravstveniRadnikSaglasnost.LicneInformacijeLekara }
     * 
     */
    public Saglasnost.ZdravstveniRadnikSaglasnost.LicneInformacijeLekara createSaglasnostZdravstveniRadnikSaglasnostLicneInformacijeLekara() {
        return new Saglasnost.ZdravstveniRadnikSaglasnost.LicneInformacijeLekara();
    }

    /**
     * Create an instance of {@link Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo }
     * 
     */
    public Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo createSaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfo() {
        return new Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo();
    }

    /**
     * Create an instance of {@link Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.PrivremeneKontraindikacije }
     * 
     */
    public Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.PrivremeneKontraindikacije createSaglasnostZdravstveniRadnikSaglasnostObrazacPrivremeneKontraindikacije() {
        return new Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.PrivremeneKontraindikacije();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.UstanovaSocijalneZastite }
     * 
     */
    public Saglasnost.PacijentSaglasnost.UstanovaSocijalneZastite createSaglasnostPacijentSaglasnostUstanovaSocijalneZastite() {
        return new Saglasnost.PacijentSaglasnost.UstanovaSocijalneZastite();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.Imunizacija }
     * 
     */
    public Saglasnost.PacijentSaglasnost.Imunizacija createSaglasnostPacijentSaglasnostImunizacija() {
        return new Saglasnost.PacijentSaglasnost.Imunizacija();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.LicneInformacije.Pol }
     * 
     */
    public Saglasnost.PacijentSaglasnost.LicneInformacije.Pol createSaglasnostPacijentSaglasnostLicneInformacijePol() {
        return new Saglasnost.PacijentSaglasnost.LicneInformacije.Pol();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.LicneInformacije.Adresa }
     * 
     */
    public Saglasnost.PacijentSaglasnost.LicneInformacije.Adresa createSaglasnostPacijentSaglasnostLicneInformacijeAdresa() {
        return new Saglasnost.PacijentSaglasnost.LicneInformacije.Adresa();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.LicneInformacije.Mesto }
     * 
     */
    public Saglasnost.PacijentSaglasnost.LicneInformacije.Mesto createSaglasnostPacijentSaglasnostLicneInformacijeMesto() {
        return new Saglasnost.PacijentSaglasnost.LicneInformacije.Mesto();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.LicneInformacije.Email }
     * 
     */
    public Saglasnost.PacijentSaglasnost.LicneInformacije.Email createSaglasnostPacijentSaglasnostLicneInformacijeEmail() {
        return new Saglasnost.PacijentSaglasnost.LicneInformacije.Email();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.StranoDrzavljanstvo.BrojPasosa }
     * 
     */
    public Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.StranoDrzavljanstvo.BrojPasosa createSaglasnostPacijentSaglasnostLicneInformacijeDrzavljanstvoStranoDrzavljanstvoBrojPasosa() {
        return new Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.StranoDrzavljanstvo.BrojPasosa();
    }

    /**
     * Create an instance of {@link Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.RepublikaSrbija.JMBG }
     * 
     */
    public Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.RepublikaSrbija.JMBG createSaglasnostPacijentSaglasnostLicneInformacijeDrzavljanstvoRepublikaSrbijaJMBG() {
        return new Saglasnost.PacijentSaglasnost.LicneInformacije.Drzavljanstvo.RepublikaSrbija.JMBG();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", name = "NezeljanaReakcija", scope = Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class)
    public JAXBElement<String> createSaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoNezeljanaReakcija(String value) {
        return new JAXBElement<String>(_SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoNezeljanaReakcija_QNAME, String.class, Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", name = "DatumDavanjaVakcine", scope = Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class)
    public JAXBElement<XMLGregorianCalendar> createSaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoDatumDavanjaVakcine(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoDatumDavanjaVakcine_QNAME, XMLGregorianCalendar.class, Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Proizvodjac }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", name = "NazivVakcine", scope = Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class)
    public JAXBElement<Proizvodjac> createSaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoNazivVakcine(Proizvodjac value) {
        return new JAXBElement<Proizvodjac>(_SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoNazivVakcine_QNAME, Proizvodjac.class, Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", name = "SerijaVakcine", scope = Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class)
    public JAXBElement<String> createSaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoSerijaVakcine(String value) {
        return new JAXBElement<String>(_SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoSerijaVakcine_QNAME, String.class, Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Proizvodjac }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", name = "Proizvodjac", scope = Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class)
    public JAXBElement<Proizvodjac> createSaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoProizvodjac(Proizvodjac value) {
        return new JAXBElement<Proizvodjac>(_SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoProizvodjac_QNAME, Proizvodjac.class, Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", name = "NacinDavanjeVakcine", scope = Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class)
    public JAXBElement<String> createSaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoNacinDavanjeVakcine(String value) {
        return new JAXBElement<String>(_SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoNacinDavanjeVakcine_QNAME, String.class, Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http:///www.ftn.uns.ac.rs/vakcinacija/saglasnost", name = "Ekstremitet", scope = Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class)
    public JAXBElement<String> createSaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoEkstremitet(String value) {
        return new JAXBElement<String>(_SaglasnostZdravstveniRadnikSaglasnostObrazacVakcineInfoEkstremitet_QNAME, String.class, Saglasnost.ZdravstveniRadnikSaglasnost.Obrazac.VakcineInfo.class, value);
    }

}
