//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.11 at 07:36:04 PM CET 
//

@XmlSchema( 
		   namespace = XMLNamespaceKonstante.NAMESPACE_SAGLASNOST,
		   elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
		   xmlns = {@javax.xml.bind.annotation.XmlNs(prefix = "sa", namespaceURI=XMLNamespaceKonstante.NAMESPACE_SAGLASNOST),
				   	@javax.xml.bind.annotation.XmlNs(prefix="pred", namespaceURI=XMLNamespaceKonstante.PREDICATE),
				   	@javax.xml.bind.annotation.XmlNs(prefix = "ct", namespaceURI=XMLNamespaceKonstante.NAMESPACE_COMMON_TYPES),
        			@javax.xml.bind.annotation.XmlNs(prefix="xs", namespaceURI="http://www.w3.org/2001/XMLSchema")}
          )

package com.xml.vakcinacija.model.saglasnost;
import com.xml.vakcinacija.utils.*;
import javax.xml.bind.annotation.XmlSchema;